<?php

declare( strict_types = 1 );

namespace WMDE\Fundraising\DonationContext\Tests\Integration\DataAccess;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Exception\ORMException;
use Doctrine\ORM\Query;
use Doctrine\ORM\QueryBuilder;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use WMDE\Fundraising\DonationContext\DataAccess\DoctrineDonationExistsChecker;
use WMDE\Fundraising\DonationContext\DataAccess\DoctrineDonationRepository;
use WMDE\Fundraising\DonationContext\DataAccess\DoctrineEntities\Donation as DoctrineDonation;
use WMDE\Fundraising\DonationContext\DataAccess\DoctrineEntities\DonationTracking;
use WMDE\Fundraising\DonationContext\DataAccess\DonorFactory;
use WMDE\Fundraising\DonationContext\DataAccess\DonorFieldMapper;
use WMDE\Fundraising\DonationContext\DataAccess\LegacyConverters\DataBlobScrubber;
use WMDE\Fundraising\DonationContext\DataAccess\LegacyConverters\DomainToLegacyConverter;
use WMDE\Fundraising\DonationContext\DataAccess\LegacyConverters\LegacyToDomainConverter;
use WMDE\Fundraising\DonationContext\DataAccess\ModerationReasonRepository;
use WMDE\Fundraising\DonationContext\Domain\DonationTrackingFetcher;
use WMDE\Fundraising\DonationContext\Domain\Model\ModerationIdentifier;
use WMDE\Fundraising\DonationContext\Domain\Model\ModerationReason;
use WMDE\Fundraising\DonationContext\Domain\Repositories\GetDonationException;
use WMDE\Fundraising\DonationContext\Domain\Repositories\StoreDonationException;
use WMDE\Fundraising\DonationContext\Tests\Data\ValidDoctrineDonation;
use WMDE\Fundraising\DonationContext\Tests\Data\ValidDonation;
use WMDE\Fundraising\DonationContext\Tests\Data\ValidPayments;
use WMDE\Fundraising\DonationContext\Tests\Fixtures\FailingDonationExistsChecker;
use WMDE\Fundraising\DonationContext\Tests\Fixtures\SucceedingDonationExistsChecker;
use WMDE\Fundraising\DonationContext\Tests\TestEnvironment;
use WMDE\Fundraising\PaymentContext\Domain\Model\LegacyPaymentData;
use WMDE\Fundraising\PaymentContext\UseCases\GetPayment\GetPaymentUseCase;

#[CoversClass( DoctrineDonationRepository::class )]
#[CoversClass( DonorFieldMapper::class )]
#[CoversClass( DonorFactory::class )]
#[CoversClass( DoctrineDonation::class )]
#[CoversClass( DomainToLegacyConverter::class )]
#[CoversClass( LegacyToDomainConverter::class )]
#[CoversClass( DataBlobScrubber::class )]
class DoctrineDonationRepositoryTest extends TestCase {

	private const ID_OF_DONATION_NOT_IN_DB = 35505;

	private EntityManager $entityManager;
	private ModerationReasonRepository $moderationRepository;

	private LegacyPaymentData $legacyPaymentData;

	public function setUp(): void {
		$factory = TestEnvironment::newInstance()->getFactory();
		$this->entityManager = $factory->getEntityManager();
		$this->moderationRepository = new ModerationReasonRepository( $this->entityManager );
		parent::setUp();
		$this->legacyPaymentData = $this->createDefaultLegacyData();
	}

	public function testValidDonationGetsPersisted(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();
		$this->newRepository()->storeDonation( $donation );

		$expectedDoctrineEntity = ValidDoctrineDonation::newDirectDebitDoctrineDonation();
		$expectedDoctrineEntity->setId( $donation->getId() );
		$trackingInfo = $donation->getTrackingInfo();
		$expectedDoctrineEntity->setDonationTracking( new DonationTracking( $trackingInfo->campaign, $trackingInfo->keyword ) );

		$this->assertDoctrineEntityIsInDatabase( $expectedDoctrineEntity );
	}

	private function newRepository(): DoctrineDonationRepository {
		return new DoctrineDonationRepository(
			$this->entityManager,
			new DoctrineDonationExistsChecker( $this->entityManager ),
			$this->makeGetPaymentUseCaseStub(),
			$this->moderationRepository
		);
	}

	private function assertDoctrineEntityIsInDatabase( DoctrineDonation $expected ): void {
		$this->assertNotNull( $expected->getId() );
		$actual = $this->getDoctrineDonationById( $expected->getId() );

		// compare data blobs
		$this->assertEquals( $expected->getDecodedData(), $actual->getDecodedData() );

		// creationTime is autogenerated when saving
		$expected->setCreationTime( $actual->getCreationTime() );

		// check for value equality of moderation reasons
		$this->assertEquals( $expected->getModerationReasons()->toArray(), $actual->getModerationReasons()->toArray() );
		// reset the moderation reasons because doctrine sets the moderation reasons to a PersistedCollection instead of ArrayCollection
		// this way we can compare the objects
		/**
		 * @var ModerationReason[] $moderationReasons
		 */
		$moderationReasons = $expected->getModerationReasons()->toArray();
		$actual->setModerationReasons( ...$moderationReasons );

		// Compare tracking values, then reset them
		// We do this because we initialize the expected DoctrineDonation with an unpersisted tracking (id property is `null`)
		// The repository always uses the DatabaseDonationTrackingFinder to find or create a persisted tracking
		// Comparing expected and actual later on would always fail because expected has no id.
		$this->assertNotNull( $actual->getDonationTracking() );
		$this->assertNotNull( $expected->getDonationTracking(), 'Check you test setup - you should always expect a filled DonationTracking' );
		$this->assertSame( $expected->getDonationTracking()->campaign, $actual->getDonationTracking()->campaign );
		$this->assertSame( $expected->getDonationTracking()->keyword, $actual->getDonationTracking()->keyword );
		$expected->setDonationTracking( $actual->getDonationTracking() );

		$this->assertEquals( $expected, $actual );
	}

	private function getDoctrineDonationById( int $id ): DoctrineDonation {
		$donationRepo = $this->entityManager->getRepository( DoctrineDonation::class );
		$donation = $donationRepo->find( $id );
		$this->assertInstanceOf( DoctrineDonation::class, $donation );
		return $donation;
	}

	public function testWhenInsertFails_domainExceptionIsThrown(): void {
		$donation = ValidDonation::newDirectDebitDonation();

		$repository = new DoctrineDonationRepository(
			$this->newEntityManagerThatThrowsOnPersist(),
			new SucceedingDonationExistsChecker(),
			$this->makeGetPaymentUseCaseStub(),
			$this->moderationRepository
		);

		$this->expectException( StoreDonationException::class );
		$repository->storeDonation( $donation );
	}

	public function testNewDonationPersistenceRoundTrip(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();

		$repository = $this->newRepository();

		$repository->storeDonation( $donation );
		// find() will retrieve a cached value, so we should clear the entity cache here
		$this->entityManager->clear();

		$this->assertEquals(
			$donation,
			$repository->getDonationById( $donation->getId() )
		);
	}

	public function testNewModeratedDonationPersistenceRoundTrip(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$donation->markForModeration( new ModerationReason( ModerationIdentifier::ADDRESS_CONTENT_VIOLATION ) );

		$repository = $this->newRepository();

		$repository->storeDonation( $donation );
		// find() will retrieve a cached value, so we should clear the entity cache here
		$this->entityManager->clear();

		$storedDonation = $repository->getDonationById( $donation->getId() );

		$this->assertNotNull( $storedDonation );
		$this->assertEquals(
			$donation->getModerationReasons(),
			$storedDonation->getModerationReasons()
		);
	}

	public function testScrubbedDonationPersistenceRoundTrip(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();
		$donation->markAsExported( new \DateTimeImmutable( '2024-06-21 00:05:00' ) );
		$donation->scrubPersonalData(
			externalIncompleteGracePeriodCutoffDate:  new \DateTimeImmutable(),
			moderationGracePeriodCutoffDate: new \DateTimeImmutable()
		);

		$repository = $this->newRepository();

		$repository->storeDonation( $donation );
		// find() will retrieve a cached value, so we should clear the entity cache here
		$this->entityManager->clear();

		$this->assertTrue( $donation->donorIsScrubbed() );
		$this->assertEquals(
			$donation,
			$repository->getDonationById( $donation->getId() )
		);
	}

	public function testWhenDonationAlreadyExists_persistingCausesUpdate(): void {
		$repository = $this->newRepository();

		$donation = ValidDonation::newDirectDebitDonation();
		$repository->storeDonation( $donation );

		// It is important a new instance is created here to test "detached entity" handling
		$newDonation = ValidDonation::newDirectDebitDonation( $donation->getId() );
		$newDonation->markForModeration( new ModerationReason( ModerationIdentifier::MANUALLY_FLAGGED_BY_ADMIN ) );
		$repository->storeDonation( $newDonation );

		$this->assertEquals( $newDonation, $repository->getDonationById( $donation->getId() ) );
	}

	public function testWhenDonationDoesNotExist_getDonationReturnsNull(): void {
		$repository = $this->newRepository();

		$this->assertNull( $repository->getDonationById( self::ID_OF_DONATION_NOT_IN_DB ) );
	}

	public function testWhenDoctrineThrowsException_domainExceptionIsThrown(): void {
		$repository = new DoctrineDonationRepository(
			$this->newEntityManagerThatThrowsWithQueryBuilder(),
			new SucceedingDonationExistsChecker(),
			$this->makeGetPaymentUseCaseStub(),
			$this->moderationRepository
		);

		$this->expectException( GetDonationException::class );
		$repository->getDonationById( self::ID_OF_DONATION_NOT_IN_DB );
	}

	public function testGivenDonationUpdateWithAnonymousDonor_DonorInfoIsCleared(): void {
		$donation = ValidDonation::newBookedPayPalDonation();
		$this->newRepository()->storeDonation( $donation );

		$anonymousDonation = ValidDonation::newBookedAnonymousPayPalDonationUpdate( $donation->getId() );
		$this->newRepository()->storeDonation( $anonymousDonation );

		$doctrineDonation = $this->getDoctrineDonationById( $donation->getId() );

		$this->assertSame( 'Anonym', $doctrineDonation->getDonorFullName() );
		$this->assertSame( '', $doctrineDonation->getDonorCity() );
		$this->assertSame( '', $doctrineDonation->getDonorEmail() );
		$this->assertSame( $donation->getTrackingInfo()->totalImpressionCount, $doctrineDonation->getImpressionCount() );
		$this->assertSame( $donation->getTrackingInfo()->singleBannerImpressionCount, $doctrineDonation->getBannerImpressionCount() );
		$this->assertSame( $donation->getTrackingInfo()->totalImpressionCount, $doctrineDonation->getDecodedData()[ 'impCount' ] );
		$this->assertSame( $donation->getTrackingInfo()->singleBannerImpressionCount, $doctrineDonation->getDecodedData()[ 'bImpCount' ] );
		$this->assertSame( $donation->getTrackingInfo()->getTrackingString(), $doctrineDonation->getDecodedData()[ 'tracking' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'titel' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'vorname' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'nachname' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'strasse' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'plz' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'ort' ] );
		$this->assertNull( $doctrineDonation->getDecodedData()[ 'email' ] );
	}

	public function testCommentGetPersistedAndRetrieved(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();
		$donation->addComment( ValidDonation::newPublicComment() );

		$repository = $this->newRepository();
		$repository->storeDonation( $donation );

		$retrievedDonation = $repository->getDonationById( $donation->getId() );

		$this->assertEquals( $donation, $retrievedDonation );
	}

	public function testPersistingDonationWithoutCommentCausesCommentToBeCleared(): void {
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();
		$donation = ValidDonation::newDirectDebitDonation();
		$donation->addComment( ValidDonation::newPublicComment() );

		$repository = $this->newRepository();
		$repository->storeDonation( $donation );

		$newDonation = ValidDonation::newDirectDebitDonation( $donation->getId() );

		$repository->storeDonation( $newDonation );

		$expectedDoctrineEntity = ValidDoctrineDonation::newDirectDebitDoctrineDonation();
		$expectedDoctrineEntity->setId( $donation->getId() );
		$expectedDoctrineEntity->setComment( '' );
		$expectedDoctrineEntity->setIsPublic( false );
		$expectedDoctrineEntity->setPublicRecord( '' );
		$trackingInfo = $donation->getTrackingInfo();
		$expectedDoctrineEntity->setDonationTracking( new DonationTracking( $trackingInfo->campaign, $trackingInfo->keyword ) );

		$this->assertDoctrineEntityIsInDatabase( $expectedDoctrineEntity );
	}

	public function testWhenUpdateFails_domainExceptionIsThrown(): void {
		$donation = ValidDonation::newDirectDebitDonation( 42 );
		$trackingFetcher = $this->createConfiguredStub(
			DonationTrackingFetcher::class,
			[ 'getTracking' => new DonationTracking( '', '' ) ]
		);

		$repository = new DoctrineDonationRepository(
			$this->newEntityManagerThatThrowsOnPersist(),
			new FailingDonationExistsChecker(),
			$this->makeGetPaymentUseCaseStub(),
			$this->moderationRepository,
			$trackingFetcher
		);

		$this->expectException( StoreDonationException::class );
		$repository->storeDonation( $donation );
	}

	public function makeGetPaymentUseCaseStub(): GetPaymentUseCase {
		return $this->createConfiguredStub(
			GetPaymentUseCase::class,
			[ 'getLegacyPaymentDataObject' => $this->legacyPaymentData ]
		);
	}

	private function createDefaultLegacyData(): LegacyPaymentData {
		// Bogus data
		return new LegacyPaymentData(
			999999,
			999,
			'PPL',
			[
				'paymentValue' => 'almostInfinite',
				'paid' => 'certainly'
			],
		);
	}

	public function testGivenTwoDonationsWithTheSameModerationReason_ReasonIsNotCreatedMultipleTimesButReused(): void {
		$donation1 = ValidDonation::newDirectDebitDonation();
		$donation1->markForModeration( new ModerationReason( ModerationIdentifier::ADDRESS_CONTENT_VIOLATION ) );
		$donation2 = ValidDonation::newDirectDebitDonation();
		$donation2->markForModeration( new ModerationReason( ModerationIdentifier::ADDRESS_CONTENT_VIOLATION ) );

		$repository = $this->newRepository();
		$repository->storeDonation( $donation1 );
		$repository->storeDonation( $donation2 );

		$connection = $this->entityManager->getConnection();
		$result = $connection->executeQuery( "SELECT COUNT(*) FROM donation_moderation_reason " );
		$this->assertSame( 1, $result->fetchOne() );
	}

	public function testWhenScrubbingDonation_repositoryRemovesDataAndSets(): void {
		$donationId = 3;
		$donation = ValidDonation::newBookedPayPalDonation( $donationId );
		$donation->markAsExported();
		$repository = $this->newRepository();
		$repository->storeDonation( $donation );
		$this->entityManager->clear();

		$donation->scrubPersonalData(
			externalIncompleteGracePeriodCutoffDate: new \DateTimeImmutable(),
			moderationGracePeriodCutoffDate: new \DateTimeImmutable()
		);
		$repository->storeDonation( $donation );

		$connection = $this->entityManager->getConnection();
		$row = $connection->executeQuery( "SELECT * FROM spenden WHERE id=$donationId" )->fetchAssociative();
		$this->assertIsArray( $row );
		$this->assertSame( 1, $row['is_scrubbed'], 'Donation scrub status should be true' );
		$this->assertSame( '', $row['name'], 'Should remove full name' );
		$this->assertSame( '', $row['email'], 'Should remove email address' );
		$this->assertSame( '', $row['ort'], 'Should remove city' );
		$this->assertSame( '', $row['ueb_code'], ' Should remove bank transfer code' );
		// @phpstan-ignore argument.type
		$data = unserialize( base64_decode( $row['data'] ) );
		$this->assertIsArray( $data );

		$this->assertEquals( [
			'impCount' => 3,
			'bImpCount' => 1,
			'tracking' => 'test/gelb',
			'anrede' => 'nyan',
			'adresstyp' => 'person'
		], $data );
	}

	public function testWhenScrubbingDonation_allUnneededDataISClearedFromDataBlob(): void {
		$donationId = 3;
		$donation = ValidDonation::newBookedPayPalDonation( $donationId );
		$donation->markAsExported();
		$repository = $this->newRepository();
		$repository->storeDonation( $donation );
		$this->entityManager->clear();

		$connection = $this->entityManager->getConnection();
		$row = $connection->executeQuery( "SELECT data FROM spenden WHERE id = $donationId" )->fetchAssociative();
		// @phpstan-ignore argument.type, offsetAccess.nonOffsetAccessible
		$data = unserialize( base64_decode( $row['data'] ) );
		// @phpstan-ignore offsetAccess.nonOffsetAccessible
		$data[ 'unexpected_pii_data' ] = 'Jasper Carrott';
		$serialisedData = base64_encode( serialize( $data ) );
		$connection->executeQuery( "UPDATE spenden SET data = '$serialisedData' WHERE id = $donationId" );

		$donation->scrubPersonalData(
			externalIncompleteGracePeriodCutoffDate: new \DateTimeImmutable(),
			moderationGracePeriodCutoffDate: new \DateTimeImmutable()
		);
		$repository->storeDonation( $donation );

		$connection = $this->entityManager->getConnection();
		$row = $connection->executeQuery( "SELECT * FROM spenden WHERE id=$donationId" )->fetchAssociative();
		$this->assertIsArray( $row );
		// @phpstan-ignore argument.type
		$data = unserialize( base64_decode( $row['data'] ) );
		$this->assertIsArray( $data );

		$this->assertEquals( [
			'impCount' => 3,
			'bImpCount' => 1,
			'tracking' => 'test/gelb',
			'anrede' => 'nyan',
			'adresstyp' => 'person'
		], $data );
	}

	public function testPublicCommentStaysPersistedWhenDonationIsScrubbed(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();
		$donation->addComment( ValidDonation::newPublicComment() );

		$repository = $this->newRepository();
		$repository->storeDonation( $donation );
		$this->entityManager->clear();

		$retrievedDonation = $repository->getDonationById( $donation->getId() );
		$comment = $retrievedDonation?->getComment();

		$this->assertNotNull( $comment );
		$this->assertSame( ValidDonation::COMMENT_IS_PUBLIC, $comment->isPublic() );
		$this->assertSame( ValidDonation::COMMENT_TEXT, $comment->getCommentText() );
		$this->assertSame( ValidDonation::COMMENT_AUTHOR_DISPLAY_NAME, $comment->getAuthorDisplayName() );

		$donation->markAsExported();
		$donation->scrubPersonalData( new \DateTimeImmutable(), new \DateTimeImmutable() );
		$repository->storeDonation( $donation );
		$this->entityManager->clear();

		$retrievedDonation = $repository->getDonationById( $donation->getId() );
		$comment = $retrievedDonation?->getComment();

		$this->assertTrue( $retrievedDonation?->donorIsScrubbed() );
		$this->assertNotNull( $comment );
		$this->assertEquals( ValidDonation::COMMENT_IS_PUBLIC, $comment->isPublic() );
		$this->assertEquals( ValidDonation::COMMENT_TEXT, $comment->getCommentText() );
		$this->assertEquals( ValidDonation::COMMENT_AUTHOR_DISPLAY_NAME, $comment->getAuthorDisplayName() );
	}

	public function testPrivateCommentIsRemovedWhenDonationIsScrubbed(): void {
		$donation = ValidDonation::newDirectDebitDonation();
		$this->legacyPaymentData = ValidPayments::newDirectDebitLegacyData();
		$donation->addComment( ValidDonation::newPrivateComment() );

		$repository = $this->newRepository();
		$repository->storeDonation( $donation );
		$this->entityManager->clear();

		$connection = $this->entityManager->getConnection();
		$row = $connection->executeQuery( "SELECT * FROM spenden WHERE id = {$donation->getId()}" )->fetchAssociative();
		$this->assertIsArray( $row );

		$this->assertEquals( ValidDonation::COMMENT_AUTHOR_DISPLAY_NAME, $row[ 'eintrag' ] );
		$this->assertEquals( ValidDonation::COMMENT_TEXT, $row[ 'kommentar' ] );

		$donation->markAsExported();
		$donation->scrubPersonalData( new \DateTimeImmutable(), new \DateTimeImmutable() );
		$repository->storeDonation( $donation );
		$this->entityManager->clear();

		$row = $connection->executeQuery( "SELECT * FROM spenden WHERE id = {$donation->getId()}" )->fetchAssociative();
		$this->assertIsArray( $row );

		$this->assertSame( '', $row[ 'eintrag' ] );
		$this->assertSame( '', $row[ 'kommentar' ] );
	}

	private function newEntityManagerThatThrowsWithQueryBuilder(): EntityManager {
		$query = $this->createStub( Query::class );
		$query->method( 'getOneOrNullResult' )
			->willThrowException( new class() extends \RuntimeException implements ORMException {
			} );

		$qb = $this->createStub( QueryBuilder::class );
		$qb->method( 'select' )->willReturn( $qb );
		$qb->method( 'from' )->willReturn( $qb );
		$qb->method( 'where' )->willReturn( $qb );
		$qb->method( 'setParameter' )->willReturn( $qb );
		$qb->method( 'getQuery' )->willReturn( $query );

		return $this->createConfiguredStub(
			EntityManager::class,
			[ 'createQueryBuilder' => $qb ]
		);
	}

	private function newEntityManagerThatThrowsOnPersist(): EntityManager {
		$stub = $this->createStub( EntityManager::class );
		$stub->method( 'persist' )
			->willThrowException( new class() extends \RuntimeException implements ORMException {
			} );
		return $stub;
	}
}
