inherit: true

tools:
    external_code_coverage:
        timeout: 3600
    php_code_sniffer: true
    php_cpd: false # PHP Copy/Paste Detector and PHP Code Similarity Analyzer cannot both be used simultaneously
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    dependency_paths:
    - 'vendor/'

build:
    nodes:
        analysis:
            tests:
                override:
                - php-scrutinizer-run
                - phpcs-run
    tests:
        override:
        - true # Disable unit tests because they are handled by Travis
