inherit: true

tools:
    php_code_sniffer: true
    php_cpd: false # PHP Copy/Paste Detector and PHP Code Similarity Analyzer cannot both be used simultaneously
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true

filter:
    dependency_paths:
    - 'vendor/'

build:
    image: default-bionic
        environment:
            php: 8.1.4
    nodes:
        analysis:
            tests:
                override:
                - php-scrutinizer-run
                - phpcs-run
    
build_failure_conditions:
    - 'project.metric_change("scrutinizer.test_coverage", < 0)'
    - 'project.metric_change("scrutinizer.quality", < -0.3)'
