language: php

services:
  - docker

php:
  - 7.4

install:
  - travis_retry composer install

script:
  - composer validate --no-interaction
  - make ci

after_success:
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
