language: php

services:
  - docker

php:
  - 8.0

install:
  - travis_retry composer install

script:
  - composer validate --no-interaction
  - make ci
  - make install-php COMPOSER_FLAGS="--no-dev -q" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm ghcr.io/phpstan/phpstan analyse --level 5 -c phpstan.neon --no-progress src/ # Can't use "make stan" because stan was removed

cache:
  directories:
    - $HOME/.composer/cache
