language: php

services:
  - docker

php:
  - 7.1
  - 7.2

install:
  - travis_retry composer install

script:
  - cat ~/.travis_ci_environment.yml
  - cat ~/.phpenv
  - ls -al ~/.composer
  - composer validate --no-interaction
  - make ci

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - vendor/bin/phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
