language: php

services:
  - docker

php:
  - 7.4

install:
  - travis_retry composer install

script:
  - composer validate --no-interaction
  - make ci-with-coverage COVERAGE_FLAGS="--coverage-clover coverage.clover"
  - make install-php COMPOSER_FLAGS="--no-dev -q" # Remove dev dependencies to make sure PHPStan creates errors if prod code depends on dev classes
  - docker run -v $PWD:/app --rm ghcr.io/phpstan/phpstan analyse --level 1 --no-progress src/ # Can't use "make stan" because stan was removed

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
