version: '2'

services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      XDEBUG_CONFIG: remote_host=172.25.0.1
      PHP_IDE_CONFIG: "serverName=fundraising-donations"