version: '3.4'

services:
  app:
    image: "registry.gitlab.com/fun-tech/fundraising-frontend-docker/php-8.1:latest"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app


  database:
    image: mysql:5.6
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=fundraising
      - MYSQL_PASSWORD=INSECURE PASSWORD
      - MYSQL_DATABASE=fundraising
    volumes:
      - db-storage:/var/lib/mysql
      - ./:/usr/src/app
    expose:
      - "3306"

volumes:
  db-storage:

